#http配置服务
http:
  maxTotal: 100 #最大连接数
  defaultMaxPerRoute : 20 #并发数
  connectTimeout: 1000 #创建连接的最长时间
  connectionRequestTimeout: 500 #从连接池中获取到连接的最长时间
  socketTimeout: 10000 #数据传输的最长时间
  staleConnectionCheckEnabled: true #提交请求前测试连接是否可用